import { Buffer } from 'node:buffer';

/**
 * File status enumeration strictly following git status --porcelain=v2 format.
 *
 * - CLEAN: No changes
 * - UNTRACKED: Untracked file (??)
 * - STAGED_MODIFIED: Modified in index (M.)
 * - STAGED_ADDED: Added to index (A.)
 * - STAGED_DELETED: Deleted from index (D.)
 * - UNSTAGED_MODIFIED: Modified in worktree but not index (.M)
 * - UNSTAGED_DELETED: Deleted from worktree but not index (.D)
 * - MM: Modified in both index and worktree (Double Dirty)
 * - CONFLICT: Merge conflict (UU/AA/DD)
 */
export enum FileStatus {
  // Clean state
  CLEAN = 'CLEAN',
  UNTRACKED = 'UNTRACKED',

  // Staged states
  STAGED_MODIFIED = 'STAGED_MODIFIED',
  STAGED_ADDED = 'STAGED_ADDED',
  STAGED_DELETED = 'STAGED_DELETED',

  // Worktree states
  UNSTAGED_MODIFIED = 'UNSTAGED_MODIFIED',
  UNSTAGED_DELETED = 'UNSTAGED_DELETED',

  // Double Dirty state
  MM = 'MM',

  // Conflict state
  CONFLICT = 'CONFLICT',
}

/**
 * Complete description of a file's state.
 */
export interface FileState {
  path: string;
  absolutePath?: string; // Optional because it was added later, but Resolver populates it.
  status: FileStatus;
  isBinary: boolean;
  isSymlink: boolean;
  isIgnored: boolean; // [Added] Required for safety guards to prevent overwriting user's ignored files

  // Metadata
  size: number;
  mtime?: number;

  // For MM state only
  stagedContent?: Buffer;
  workingContent?: Buffer;
}

/**
 * Operation semantic types.
 * Defines whether the content should be treated as a full file or a patch.
 */
export enum OpType {
  PATCH = 'PATCH', // Incremental changes (Unified Diff)
  OVERWRITE = 'OVERWRITE', // Full file replacement (New files or force overwrite)
  DELETE = 'DELETE', // Removal of file
}

/**
 * Operation generated by AI.
 */
export interface ShadowOperation {
  type: OpType;
  path: string; // Relative path to repo root
  content?: Buffer; // New content (for OVERWRITE) or Diff text (for PATCH)
  shadowPath?: string; // Path in shadow worktree

  encoding?: string; // Default 'utf8'
  lineEnding?: 'lf' | 'crlf' | 'auto';
  isBinary?: boolean; // Hint from diff parser
}

/**
 * Options for the transaction.
 */
export interface GrizzcoOptions {
  force: boolean; // applyBackOnDirty === 'dirtySnapshot'
  allowMM: boolean; // applyBackOnDirty === '3way'
  safeMode: boolean; // Always true in production
  rejectDir: string; // Default .s8p/rejections
  dryRun: boolean;

  maxFileSize: number;
  verbose?: string;
  targetNodeName?: string;

  // List of operations to perform
  operations: ShadowOperation[];
}

/**
 * Runtime context for a single file transaction.
 */
export interface TransactionContext {
  repoRoot: string;

  // 1. File State
  file: {
    path: string;
    absolutePath?: string; // Optional because it was added later, but Resolver populates it.
    status: FileStatus;
    isBinary: boolean;
    isSymlink: boolean;
    isIgnored: boolean; // [Added] Required for safety guards
    hasConflict: boolean;
    size: number;

    // MM specific
    stagedContent?: Buffer;
    workingContent?: Buffer;
  };

  // 2. AI Operation
  operation: ShadowOperation;

  // 3. User Options
  options: Omit<GrizzcoOptions, 'operations'>;

  // 4. System State
  snapshot: {
    exists: boolean;
    id: string;
    timestamp: number;
    path: string;
  };

  // 5. Runtime State
  runtime: {
    selectedWorker?: string;
    mergedContent?: Buffer;
    needsRollback: boolean;
    rejectionReason?: string;
    generateRejectionFile?: boolean;
    executionTime?: number;
    tempFilePath?: string;
    checkpointHash?: string;
  };
}

/**
 * Result of a worker execution.
 */
export interface MergeResult {
  path: string;
  success: boolean;
  mergedContent?: Buffer;
  error?: string;
  isConflict: boolean;

  workerId: string;
  executionTime: number;
  conflictMarkers?: string[];
}

/**
 * Overall transaction result.
 */
export interface TransactionResult {
  success: boolean;
  totalFiles: number;
  successCount: number;
  failureCount: number;

  results: Array<{
    path: string;
    success: boolean;
    workerId?: string;
    error?: string;
    decisionTree?: string;
  }>;

  snapshot: {
    created: boolean;
    rolledBack: boolean;
    snapshotId?: string;
  };

  performance: {
    totalTime: number;
    stateResolutionTime: number;
    mergeTime: number;
    ioTime: number;
  };
}

/**
 * Snapshot object structure
 */
export interface Snapshot {
  id: string;
  timestamp: number;
}
