name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
