# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      bun-version:
        required: false
        type: string
        default: '1.3.9'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          bun-version: ${{ inputs.bun-version }}
      - name: Verify
        run: bun run verify
